services:
  api:
    image: franint/api-repo:test-version # prioriza buscarla en remoto
    build:
      context: .
      dockerfile: Dockerfile.api # si se usa --build Construimos la imagen y la guardamos con el nombre de arriba ↑↑
    ports:
      - 8000:8000 #IF EXPOSING EXTERNALLY NOT REQUIRED 8000 IS ENOUGH
    env_file: ".env.test"
    # environment:
    #   - EXAMPLE_KEY=EXAMPLE_VALUE
    depends_on: 
      - backend-DDBB

  backend-DDBB:
    image: postgres:16
    ports:
      - 5433:5432 #host_port:container_port # le asignamos el 5433 para que no interfiera con el postgres local
    env_file: ".env.ddbb.test"
    # environment:
    #   - POSTGRES_PASSWORD=${DDBB_PASSWORD} #Docker-compose injects the variables into the env from the .env
    #   - POSTGRES_DB=${DDBB_NAME} #Only for the first time that the container is executed
    #   - POSTGRES_USER=${DDBB_USER}
    volumes:
      - postgres-db:/var/lib/postgresql/data #Name and route
volumes:
  postgres-db: # THIS MAKES THE VOLUME ACCESIBLE FOR THE OTHER SERVICES/CONTAINERS