
# This workflow is intended for pytest
name: Build and Deploy code
#on: [push, pull_request] 
on:
  push:
    tags:
      - "v*.*.*"

  pull_request:

    branches:
      - "test_workflow"
      - "linux"

jobs: #Job= set of steps that run in the same machine. Each job can run in different runner if not specified
  test: #Job name
    env:
      

      SQLALCHEMY_DATABASE_URL: ${{secrets.SQLALCHEMY_DATABASE_URL}}
      ALEMBIC_DATABASE_URL: ${{secrets.ALEMBIC_DATABASE_URL_TEST}}

      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 15

      MAIL_USERNAME: ${{secrets.MAIL_USERNAME}}
      MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
      MAIL_FROM: "fbernal.jmzafra@gmail.com"
      MAIL_PORT: 2525
      MAIL_SERVER: "smtp.mailmug.net"
      MAIL_STARTTLS: "False"
      MAIL_SSL_TLS: "False"

    runs-on: ubuntu-latest
    #if: github.ref_name == 'test_workflow' || github.ref_name == 'linux' does not work with tags

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER_TEST }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_TEST }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB_TEST }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:   
      - name: pulling repo
        uses: actions/checkout@v7 #pre-build action for pulling 
      - name: setup-python 3.12
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'
      
      - name: upgrade pip
        run: python -m pip install --upgrade pip
      - name: install requirements
        run: pip install -r "requirements.txt"
      - name: verify packages
        run: pip list 
      - name: run alembic
        run: alembic upgrade head

      - name: pytest
        run: |
         pip install pytest
         pytest -v -s test/
  Docker:

    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: pulling repo
        uses: actions/checkout@v7 #pre-build action for pulling 
        
      - name: login ghcr
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REPO_TOKEN }}
      - name: build image
        uses: docker/setup-buildx-action@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          # we are just providing the format of the name for build and push
          images: |
            ghcr.io/${{ github.repository_owner }}/fastapi
          tags: |
            
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and Push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile.api
          push: true
          tags: ${{ steps.meta.outputs.tags }}     # Apply the generated string tags
          labels: ${{ steps.meta.outputs.labels }} # Bake the generated OCI metadata into the image

    
      
      

  

        
